import telebot

botTimeWeb = telebot.TeleBot('6317515579:AAF7m_24C_PG9e9-5YeX9yaaUfRO6llFU6Q')

from telebot import types
import sqlite3

list1 = []
list2 = []
list3 = []
txt = ""
flag = -1

@botTimeWeb.message_handler(commands=['start'])
def startBot(message):
    first_mess = f"<b>{message.from_user.first_name} {message.from_user.last_name}</b>, здраствуйте,\nЯ телеграмм-бот, который поможет найти информацию о достопримечательностях Санкт-Петербурга\nВыберите способ поиска"
    markup = types.InlineKeyboardMarkup()
    rayon = types.InlineKeyboardButton(text='Поиск по району', callback_data='rayon_message')
    markup.row(rayon)
    street = types.InlineKeyboardButton(text='Поиск по улице', callback_data='street_message')
    markup.row(street)
    test = types.InlineKeyboardButton(text='Поиск по названию', callback_data='name_message')
    markup.row(test)
    botTimeWeb.send_message(message.chat.id, first_mess, parse_mode='html', reply_markup=markup)

@botTimeWeb.callback_query_handler(func=lambda c: True)
def inlin(c):
    if c.data == 'main_menu':
        mainmenu = types.InlineKeyboardMarkup()
        rayon = types.InlineKeyboardButton(text='Поиск по району', callback_data='rayon_message')
        mainmenu.add(rayon)
        street = types.InlineKeyboardButton(text='Поиск по улице', callback_data='street_message')
        mainmenu.add(street)
        name = types.InlineKeyboardButton(text='Поиск по названию', callback_data='name_message')
        mainmenu.add(name)
        botTimeWeb.send_message(c.message.chat.id, "Выберите способ поиска", parse_mode='html', reply_markup=mainmenu)
        list1.clear()
        list2.clear()
        list3.clear()
    if c.data == 'rayon_message':
        first_mess = f"Выбирете интересующий район"
        botTimeWeb.send_photo(c.message.chat.id, open('районное деление.png', 'rb'))
        mainmenu = types.InlineKeyboardMarkup()
        admiral = types.InlineKeyboardButton(text='Адмиралтейский', callback_data='admiral')
        vaska = types.InlineKeyboardButton(text='Василеостровский', callback_data='vaska')
        mainmenu.add(admiral, vaska)
        viborg = types.InlineKeyboardButton(text='Выборгский', callback_data='viborg')
        kalinin = types.InlineKeyboardButton(text='Калининский', callback_data='kalinin')
        mainmenu.add(viborg, kalinin)
        kirov = types.InlineKeyboardButton(text='Кировский', callback_data='kirov')
        kolpin = types.InlineKeyboardButton(text='Колпинский', callback_data='kolpin')
        mainmenu.add(kirov, kolpin)
        krgvard = types.InlineKeyboardButton(text='Красногвардейский', callback_data='krgvard')
        krsel = types.InlineKeyboardButton(text='Красносельский', callback_data='krsel')
        mainmenu.add(krgvard, krsel)
        kronsht = types.InlineKeyboardButton(text='Кронштатский', callback_data='kronsht')
        kurort = types.InlineKeyboardButton(text='Курортный', callback_data='kurort')
        mainmenu.add(kronsht, kurort)
        moskov = types.InlineKeyboardButton(text='Московский', callback_data='moskov')
        nevsk = types.InlineKeyboardButton(text='Невский', callback_data='nevsk')
        mainmenu.add(moskov, nevsk)
        petrograd = types.InlineKeyboardButton(text='Петроградский', callback_data='petrograd')
        petrodvor = types.InlineKeyboardButton(text='Петродворцовый', callback_data='petrodvor')
        mainmenu.add(petrograd, petrodvor)
        primorsk = types.InlineKeyboardButton(text='Приморский', callback_data='primorsk')
        pushkin = types.InlineKeyboardButton(text='Пушкинский', callback_data='pushkin')
        mainmenu.add(primorsk, pushkin)
        frunz = types.InlineKeyboardButton(text='Фрунзенский', callback_data='frunz')
        central = types.InlineKeyboardButton(text='Центральный', callback_data='central')
        mainmenu.add(frunz, central)
        back = types.InlineKeyboardButton(text='В главное меню', callback_data='main_menu')
        mainmenu.add(back)
        botTimeWeb.send_message(c.message.chat.id, first_mess, parse_mode='html', reply_markup=mainmenu)
    first_mess = f"Выбирете интересующий округ"
    if c.data == 'admiral':
        botTimeWeb.send_photo(c.message.chat.id, open('Адмиралтейский.png', 'rb'))
        menu = types.InlineKeyboardMarkup()
        admiral_AO = types.InlineKeyboardButton(text='Адмиралтейский', callback_data='admiral_AO')
        ekant_AO = types.InlineKeyboardButton(text='Екантерингофский', callback_data='ekant_AO')
        menu.add(admiral_AO, ekant_AO)
        izmail_AO = types.InlineKeyboardButton(text='Измайловский', callback_data='izmail_AO')
        kolomna_AO = types.InlineKeyboardButton(text='Коломна', callback_data='kolomna_AO')
        menu.add(izmail_AO, kolomna_AO)
        semyon_AO = types.InlineKeyboardButton(text='Семёновский', callback_data='semyon_AO')
        sennoy_AO = types.InlineKeyboardButton(text='Сенной', callback_data='sennoy_AO')
        menu.add(semyon_AO, sennoy_AO)
        back = types.InlineKeyboardButton(text='Назад', callback_data='rayon_message')
        menu.add(back)
        botTimeWeb.send_message(c.message.chat.id, first_mess, parse_mode='html', reply_markup=menu)
    if c.data == 'vaska':
        botTimeWeb.send_photo(c.message.chat.id, open('Василеостровский.png', 'rb'))
        menu = types.InlineKeyboardMarkup()
        seven_AO = types.InlineKeyboardButton(text='7-й Округ', callback_data='seven_AO')
        vasil_AO = types.InlineKeyboardButton(text='Васильевский', callback_data='vasil_AO')
        menu.add(seven_AO, vasil_AO)
        gavan_AO = types.InlineKeyboardButton(text='Гавань', callback_data='gavan_AO')
        morskoy_AO = types.InlineKeyboardButton(text='Морской', callback_data='morskoy_AO')
        menu.add(gavan_AO, morskoy_AO)
        dekabr_AO = types.InlineKeyboardButton(text='Остров Декабристов', callback_data='dekabr_AO')
        port_AO = types.InlineKeyboardButton(text='Порт', callback_data='port_AO')
        menu.add(dekabr_AO, port_AO)
        back = types.InlineKeyboardButton(text='Назад', callback_data='rayon_message')
        menu.add(back)
        botTimeWeb.send_message(c.message.chat.id, first_mess, parse_mode='html', reply_markup=menu)
    if c.data == 'viborg':
        botTimeWeb.send_photo(c.message.chat.id, open('Выборгский.png', 'rb'))
        menu = types.InlineKeyboardMarkup()
        samps_AO = types.InlineKeyboardButton(text='Сампсониевский', callback_data='samps_AO')
        svetlan_AO = types.InlineKeyboardButton(text='Светлановский', callback_data='svetlan_AO')
        menu.add(samps_AO, svetlan_AO)
        sosnov_AO = types.InlineKeyboardButton(text='Сосновское', callback_data='sosnov_AO')
        fifteen_AO = types.InlineKeyboardButton(text='15-й округ', callback_data='fifteen_AO')
        menu.add(sosnov_AO, fifteen_AO)
        parnas_AO = types.InlineKeyboardButton(text='Парнас', callback_data='parnas_AO')
        ozerki_AO = types.InlineKeyboardButton(text='Озерки', callback_data='ozerki_AO')
        menu.add(parnas_AO, ozerki_AO)
        pargol_AO = types.InlineKeyboardButton(text='Парголово', callback_data='pargol_AO')
        levash_AO = types.InlineKeyboardButton(text='Левашово', callback_data='levash_AO')
        menu.add(pargol_AO, levash_AO)
        back = types.InlineKeyboardButton(text='Назад', callback_data='rayon_message')
        menu.add(back)
        botTimeWeb.send_message(c.message.chat.id, first_mess, parse_mode='html', reply_markup=menu)
    if c.data == 'kalinin':
        botTimeWeb.send_photo(c.message.chat.id, open('Калининский.png', 'rb'))
        menu = types.InlineKeyboardMarkup()
        sever_AO = types.InlineKeyboardButton(text='Северный', callback_data='sever_AO')
        promet_AO = types.InlineKeyboardButton(text='Прометей', callback_data='promet_AO')
        menu.add(sever_AO, promet_AO)
        twenone_AO = types.InlineKeyboardButton(text='21-й округ', callback_data='twenone_AO')
        akadem_AO = types.InlineKeyboardButton(text='Академическое', callback_data='akadem_AO')
        menu.add(twenone_AO, akadem_AO)
        grazhdanka_AO = types.InlineKeyboardButton(text='Гражданка', callback_data='grazhdanka_AO')
        piskarev_AO = types.InlineKeyboardButton(text='Пискарёвка', callback_data='piskarev_AO')
        menu.add(grazhdanka_AO, piskarev_AO)
        finland_AO = types.InlineKeyboardButton(text='Финляндский Округ', callback_data='finland_AO')
        menu.add(finland_AO)
        back = types.InlineKeyboardButton(text='Назад', callback_data='rayon_message')
        menu.add(back)
        botTimeWeb.send_message(c.message.chat.id, first_mess, parse_mode='html', reply_markup=menu)
    if c.data == 'kirov':
        botTimeWeb.send_photo(c.message.chat.id, open('Кировский.png', 'rb'))
        menu = types.InlineKeyboardMarkup()
        morskvor_AO = types.InlineKeyboardButton(text='Морские ворота', callback_data='morskvor_AO')
        narv_AO = types.InlineKeyboardButton(text='Нарвский', callback_data='narv_AO')
        menu.add(morskvor_AO, narv_AO)
        avtovo_AO = types.InlineKeyboardButton(text='Автово', callback_data='avtovo_AO')
        knyazh_AO = types.InlineKeyboardButton(text='Княжево', callback_data='knyazh_AO')
        menu.add(avtovo_AO, knyazh_AO)
        dachnoe_AO = types.InlineKeyboardButton(text='Дачное', callback_data='dachnoe_AO')
        ulianka_AO = types.InlineKeyboardButton(text='Ульянка', callback_data='ulianka_AO')
        menu.add(dachnoe_AO, ulianka_AO)
        krasnosel_AO = types.InlineKeyboardButton(text='Красносельская Речка', callback_data='krasnosel_AO')
        menu.add(krasnosel_AO)
        back = types.InlineKeyboardButton(text='Назад', callback_data='rayon_message')
        menu.add(back)
        botTimeWeb.send_message(c.message.chat.id, first_mess, parse_mode='html', reply_markup=menu)
    if c.data == 'kolpin':
        botTimeWeb.send_photo(c.message.chat.id, open('Колпинский.png', 'rb'))
        menu = types.InlineKeyboardMarkup()
        petrsl_AO = types.InlineKeyboardButton(text='Петро-Славянка', callback_data='petrsl_AO')
        metstr_AO = types.InlineKeyboardButton(text='Металлстрой', callback_data='metstr_AO')
        menu.add(petrsl_AO, metstr_AO)
        sapyor_AO = types.InlineKeyboardButton(text='Сапёрный', callback_data='sapyor_AO')
        pont_AO = types.InlineKeyboardButton(text='Понтонный', callback_data='pont_AO')
        menu.add(sapyor_AO, pont_AO)
        ustizhora_AO = types.InlineKeyboardButton(text='Усть-Ижора', callback_data='ustizhora_AO')
        kolpin_AO = types.InlineKeyboardButton(text='Колпино', callback_data='kolpin_AO')
        menu.add(kolpin_AO, ustizhora_AO)
        back = types.InlineKeyboardButton(text='Назад', callback_data='rayon_message')
        menu.add(back)
        botTimeWeb.send_message(c.message.chat.id, first_mess, parse_mode='html', reply_markup=menu)
    if c.data == 'krgvard':
        botTimeWeb.send_photo(c.message.chat.id, open('Красногвардейский.png', 'rb'))
        menu = types.InlineKeyboardMarkup()
        maloht_AO = types.InlineKeyboardButton(text='Малая Охта', callback_data='maloht_AO')
        bolshoht_AO = types.InlineKeyboardButton(text='Большая Охта', callback_data='bolshoht_AO')
        menu.add(maloht_AO, bolshoht_AO)
        poroh_AO = types.InlineKeyboardButton(text='Пороховое', callback_data='poroh_AO')
        rzhevka_AO = types.InlineKeyboardButton(text='Ржевка', callback_data='rzhevka_AO')
        menu.add(poroh_AO, rzhevka_AO)
        polustr_AO = types.InlineKeyboardButton(text='Полюстрово', callback_data='polustr_AO')
        menu.add(polustr_AO)
        back = types.InlineKeyboardButton(text='Назад', callback_data='rayon_message')
        menu.add(back)
        botTimeWeb.send_message(c.message.chat.id, first_mess, parse_mode='html', reply_markup=menu)
    if c.data == 'krgvard':
        botTimeWeb.send_photo(c.message.chat.id, open('Красногвардейский.png', 'rb'))
        menu = types.InlineKeyboardMarkup()
        maloht_AO = types.InlineKeyboardButton(text='Малая Охта', callback_data='maloht_AO')
        bolshoht_AO = types.InlineKeyboardButton(text='Большая Охта', callback_data='bolshoht_AO')
        menu.add(maloht_AO, bolshoht_AO)
        poroh_AO = types.InlineKeyboardButton(text='Пороховое', callback_data='poroh_AO')
        rzhevka_AO = types.InlineKeyboardButton(text='Ржевка', callback_data='rzhevka_AO')
        menu.add(poroh_AO, rzhevka_AO)
        polustr_AO = types.InlineKeyboardButton(text='Полюстрово', callback_data='polustr_AO')
        menu.add(polustr_AO)
        back = types.InlineKeyboardButton(text='Назад', callback_data='rayon_message')
        menu.add(back)
        botTimeWeb.send_message(c.message.chat.id, first_mess, parse_mode='html', reply_markup=menu)
    if c.data == 'krsel':
        botTimeWeb.send_photo(c.message.chat.id, open('Красносельский.png', 'rb'))
        menu = types.InlineKeyboardMarkup()
        krsel_AO = types.InlineKeyboardButton(text='Красное село', callback_data='krsel_AO')
        gorel_AO = types.InlineKeyboardButton(text='Горелово', callback_data='gorel_AO')
        menu.add(krsel_AO, gorel_AO)
        konst_AO = types.InlineKeyboardButton(text='Константиновское', callback_data='konst_AO')
        sosnpol_AO = types.InlineKeyboardButton(text='Сосновая Поляна', callback_data='sosnpol_AO')
        menu.add(konst_AO, sosnpol_AO)
        urick_AO = types.InlineKeyboardButton(text='Урицк', callback_data='urick_AO')
        ugozapad_AO = types.InlineKeyboardButton(text='Юго-Запад', callback_data='ugozapad_AO')
        menu.add(urick_AO, ugozapad_AO)
        uzhnoprim_AO = types.InlineKeyboardButton(text='Южно-Приморский', callback_data='polustr_AO')
        menu.add(uzhnoprim_AO)
        back = types.InlineKeyboardButton(text='Назад', callback_data='rayon_message')
        menu.add(back)
        botTimeWeb.send_message(c.message.chat.id, first_mess, parse_mode='html', reply_markup=menu)
    if c.data == 'kronsht':
        botTimeWeb.send_photo(c.message.chat.id, open('Кронштат.png', 'rb'))
        menu = types.InlineKeyboardMarkup()
        kronsht_AO = types.InlineKeyboardButton(text='Кронштат', callback_data='kronsht_AO')
        menu.add(kronsht_AO)
        back = types.InlineKeyboardButton(text='Назад', callback_data='rayon_message')
        menu.add(back)
        botTimeWeb.send_message(c.message.chat.id, first_mess, parse_mode='html', reply_markup=menu)
    if c.data == 'kurort':
        botTimeWeb.send_photo(c.message.chat.id, open('Курортный.png', 'rb'))
        menu = types.InlineKeyboardMarkup()
        sestr_AO = types.InlineKeyboardButton(text='Сестрорецк', callback_data='sestr_AO')
        pesoch_AO = types.InlineKeyboardButton(text='Песочный', callback_data='pesoch_AO')
        menu.add(sestr_AO, pesoch_AO)
        belostr_AO = types.InlineKeyboardButton(text='Белоостров', callback_data='belostr_AO')
        soln_AO = types.InlineKeyboardButton(text='Солнечное', callback_data='soln_AO')
        menu.add(belostr_AO, soln_AO)
        repino_AO = types.InlineKeyboardButton(text='Репино', callback_data='repino_AO')
        komar_AO = types.InlineKeyboardButton(text='Комарово', callback_data='komar_AO')
        menu.add(repino_AO, komar_AO)
        zelen_AO = types.InlineKeyboardButton(text='Зеленогорск', callback_data='zelen_AO')
        ushk_AO = types.InlineKeyboardButton(text='Ушково', callback_data='ushk_AO')
        menu.add(zelen_AO, ushk_AO)
        serovo_AO = types.InlineKeyboardButton(text='Серово', callback_data='serovo_AO')
        molod_AO = types.InlineKeyboardButton(text='Молодёжное', callback_data='molod_AO')
        menu.add(serovo_AO, molod_AO)
        smolyach_AO = types.InlineKeyboardButton(text='Смолячково', callback_data='smolyach_AO')
        menu.add(smolyach_AO)
        back = types.InlineKeyboardButton(text='Назад', callback_data='rayon_message')
        menu.add(back)
        botTimeWeb.send_message(c.message.chat.id, first_mess, parse_mode='html', reply_markup=menu)
    if c.data == 'moskov':
        botTimeWeb.send_photo(c.message.chat.id, open('Московский.png', 'rb'))
        menu = types.InlineKeyboardMarkup()
        mosczast_AO = types.InlineKeyboardButton(text='Московская Застава', callback_data='mosczast_AO')
        gagar_AO = types.InlineKeyboardButton(text='Гагаринское', callback_data='gagar_AO')
        menu.add(mosczast_AO, gagar_AO)
        zvyozd_AO = types.InlineKeyboardButton(text='Звёздное', callback_data='zvyozd_AO')
        novoizm_AO = types.InlineKeyboardButton(text='Новоизмайловское', callback_data='novoizm_AO')
        menu.add(zvyozd_AO, novoizm_AO)
        pulkmer_AO = types.InlineKeyboardButton(text='Пулковский Меридиан', callback_data='pulkmer_AO')
        menu.add(pulkmer_AO)
        back = types.InlineKeyboardButton(text='Назад', callback_data='rayon_message')
        menu.add(back)
        botTimeWeb.send_message(c.message.chat.id, first_mess, parse_mode='html', reply_markup=menu)
    if c.data == 'nevsk':
        botTimeWeb.send_photo(c.message.chat.id, open('Невский.png', 'rb'))
        menu = types.InlineKeyboardMarkup()
        pravober_AO = types.InlineKeyboardButton(text='Правобережный', callback_data='pravober_AO')
        okkerv_AO = types.InlineKeyboardButton(text='Оккервиль', callback_data='okkerv_AO')
        menu.add(pravober_AO, okkerv_AO)
        nevsk_AO = types.InlineKeyboardButton(text='Невский', callback_data='nevsk_AO')
        fiftyfour_AO = types.InlineKeyboardButton(text='54-й', callback_data='fiftyfour_AO')
        menu.add(nevsk_AO, fiftyfour_AO)
        narod_AO = types.InlineKeyboardButton(text='Народный', callback_data='narod_AO')
        riback_AO = types.InlineKeyboardButton(text='Рыбацкое', callback_data='riback_AO')
        menu.add(narod_AO, riback_AO)
        obuh_AO = types.InlineKeyboardButton(text='Обуховский', callback_data='obuh_AO')
        ivan_AO = types.InlineKeyboardButton(text='Ивановский', callback_data='ivan_AO')
        menu.add(obuh_AO, ivan_AO)
        nevskzast_AO = types.InlineKeyboardButton(text='Невская Застава', callback_data='nevskzast_AO')
        menu.add(nevskzast_AO)
        back = types.InlineKeyboardButton(text='Назад', callback_data='rayon_message')
        menu.add(back)
        botTimeWeb.send_message(c.message.chat.id, first_mess, parse_mode='html', reply_markup=menu)
    if c.data == 'petrograd':
        botTimeWeb.send_photo(c.message.chat.id, open('Петроградский.png', 'rb'))
        menu = types.InlineKeyboardMarkup()
        chkalov_AO = types.InlineKeyboardButton(text='Чкаловское', callback_data='chkalov_AO')
        petrov_AO = types.InlineKeyboardButton(text='Петровское', callback_data='petrov_AO')
        menu.add(chkalov_AO, petrov_AO)
        vveden_AO = types.InlineKeyboardButton(text='Введенский', callback_data='vveden_AO')
        kronv_AO = types.InlineKeyboardButton(text='Кронверкское', callback_data='kronv_AO')
        menu.add(vveden_AO, kronv_AO)
        posad_AO = types.InlineKeyboardButton(text='Посадный', callback_data='posad_AO')
        aptek_AO = types.InlineKeyboardButton(text='Аптекарский Остров', callback_data='aptek_AO')
        menu.add(posad_AO, aptek_AO)
        back = types.InlineKeyboardButton(text='Назад', callback_data='rayon_message')
        menu.add(back)
        botTimeWeb.send_message(c.message.chat.id, first_mess, parse_mode='html', reply_markup=menu)
    if c.data == 'petrodvor':
        botTimeWeb.send_photo(c.message.chat.id, open('Петродворцовый.png', 'rb'))
        menu = types.InlineKeyboardMarkup()
        petergof_AO = types.InlineKeyboardButton(text='Петергоф', callback_data='petergof_AO')
        strelna_AO = types.InlineKeyboardButton(text='Стрельна', callback_data='strelna_AO')
        menu.add(petergof_AO, strelna_AO)
        back = types.InlineKeyboardButton(text='Назад', callback_data='rayon_message')
        menu.add(back)
        botTimeWeb.send_message(c.message.chat.id, first_mess, parse_mode='html', reply_markup=menu)
    if c.data == 'primorsk':
        botTimeWeb.send_photo(c.message.chat.id, open('Приморский.png', 'rb'))
        menu = types.InlineKeyboardMarkup()
        cherrech_AO = types.InlineKeyboardButton(text='Чёрная Речка', callback_data='cherrech_AO')
        komayr_AO = types.InlineKeyboardButton(text='Комендантский Аэродром', callback_data='komayr_AO')
        menu.add(cherrech_AO, komayr_AO)
        ozerdolg_AO = types.InlineKeyboardButton(text='Озеро Долгое', callback_data='ozerdolg_AO')
        sixtyfive_AO = types.InlineKeyboardButton(text='65-й', callback_data='sixtyfive_AO')
        menu.add(ozerdolg_AO, sixtyfive_AO)
        untol_AO = types.InlineKeyboardButton(text='Юнтолово', callback_data='untol_AO')
        kolomyagi_AO = types.InlineKeyboardButton(text='Коломяги', callback_data='kolomyagi_AO')
        menu.add(untol_AO, kolomyagi_AO)
        laholg_AO = types.InlineKeyboardButton(text='Лахта-Ольгино', callback_data='laholg_AO')
        lisnos_AO = types.InlineKeyboardButton(text='Лисий Нос', callback_data='lisnos_AO')
        menu.add(laholg_AO, lisnos_AO)
        back = types.InlineKeyboardButton(text='Назад', callback_data='rayon_message')
        menu.add(back)
        botTimeWeb.send_message(c.message.chat.id, first_mess, parse_mode='html', reply_markup=menu)
    if c.data == 'pushkin':
        botTimeWeb.send_photo(c.message.chat.id, open('Пушкинский.png', 'rb'))
        menu = types.InlineKeyboardMarkup()
        pushkin_AO = types.InlineKeyboardButton(text='Пушкин', callback_data='pushkin_AO')
        alex_AO = types.InlineKeyboardButton(text='Александровская', callback_data='alex_AO')
        menu.add(pushkin_AO, alex_AO)
        shushari_AO = types.InlineKeyboardButton(text='Шушары', callback_data='shushari_AO')
        tyarlevo_AO = types.InlineKeyboardButton(text='Тярлево', callback_data='tyarlevo_AO')
        menu.add(shushari_AO, tyarlevo_AO)
        back = types.InlineKeyboardButton(text='Назад', callback_data='rayon_message')
        menu.add(back)
        botTimeWeb.send_message(c.message.chat.id, first_mess, parse_mode='html', reply_markup=menu)
    if c.data == 'frunz':
        botTimeWeb.send_photo(c.message.chat.id, open('Фрунзенский.png', 'rb'))
        menu = types.InlineKeyboardMarkup()
        balkan_AO = types.InlineKeyboardButton(text='Балканский', callback_data='balkan_AO')
        georg_AO = types.InlineKeyboardButton(text='Георгиевский', callback_data='georg_AO')
        menu.add(balkan_AO, georg_AO)
        kupchino_AO = types.InlineKeyboardButton(text='Купчино', callback_data='kupchino_AO')
        volkov_AO = types.InlineKeyboardButton(text='Волковское', callback_data='volkov_AO')
        menu.add(kupchino_AO, volkov_AO)
        seventwo_AO = types.InlineKeyboardButton(text='72-й', callback_data='seventwo_AO')
        sevenfive_AO = types.InlineKeyboardButton(text='75-й', callback_data='sevenfive_AO')
        menu.add(seventwo_AO, sevenfive_AO)
        back = types.InlineKeyboardButton(text='Назад', callback_data='rayon_message')
        menu.add(back)
        botTimeWeb.send_message(c.message.chat.id, first_mess, parse_mode='html', reply_markup=menu)
    if c.data == 'central':
        botTimeWeb.send_photo(c.message.chat.id, open('Центральный.png', 'rb'))
        menu = types.InlineKeyboardMarkup()
        dvorc_AO = types.InlineKeyboardButton(text='Дворцовый', callback_data='dvorc_AO')
        liteyn_AO = types.InlineKeyboardButton(text='Литейный', callback_data='liteyn_AO')
        menu.add(dvorc_AO, liteyn_AO)
        smoln_AO = types.InlineKeyboardButton(text='Смольнинское', callback_data='smoln_AO')
        ligyam_AO = types.InlineKeyboardButton(text='Лиговка-Ямская', callback_data='ligyam_AO')
        menu.add(smoln_AO, ligyam_AO)
        vladimir_AO = types.InlineKeyboardButton(text='Владимирская', callback_data='vladimir_AO')
        seveneight_AO = types.InlineKeyboardButton(text='78-й', callback_data='seveneight_AO')
        menu.add(vladimir_AO, seveneight_AO)
        back = types.InlineKeyboardButton(text='Назад', callback_data='rayon_message')
        menu.add(back)
        botTimeWeb.send_message(c.message.chat.id, first_mess, parse_mode='html', reply_markup=menu)
    if (c.data == 'street_message') | (c.data == 'name_message'):
        global flag
        if c.data == 'street_message':
            botTimeWeb.send_message(c.message.chat.id, 'Введите название интересующей улицы' + "\n"
                                    + "Важно: все слова нужно писать с большой буквы в именительном числе" + "\n"
                                    + "Например: Садовая Улица")
            flag = 0
        if c.data == 'name_message':
            botTimeWeb.send_message(c.message.chat.id, 'Введите название интересующего памятника' + "\n"
                                    + "Важно: все слова нужно писать с большой буквы в именительном числе" + "\n"
                                    + "Например: Исакиевский Собор")
            flag = 1
        @botTimeWeb.message_handler(content_types=['text'])
        def handle_text(message):
            global txt
            txt = message.text
            sqlite_connection = sqlite3.connect('db.db')
            cursor = sqlite_connection.cursor()
            sqlite_select_query = """SELECT * from attractions"""
            cursor.execute(sqlite_select_query)
            records = cursor.fetchall()
            k = 0
            for row in records:
                if flag == 0:
                    q = row[4]
                else:
                    q = row[0]
                if (q == txt):
                    k = k + 1
                    list1.append(row[0])
                    list2.append(row[6])
                    list3.append(row[5])
            bt = types.InlineKeyboardMarkup()
            for i in range(0, len(list1)):
                button = types.InlineKeyboardButton(text=list1[i], callback_data=list1[i] + "$")
                bt.add(button)
            back = types.InlineKeyboardButton(text='В главное меню', callback_data='main_menu')
            bt.add(back)
            botTimeWeb.send_message(c.message.chat.id, "найдено " + str(k) + " достопримечательностей",
                                    parse_mode='html',
                                    reply_markup=bt)
            cursor.close()

    if c.data[len(c.data)-2:len(c.data)] == 'AO':
        sqlite_connection = sqlite3.connect('db.db')
        cursor = sqlite_connection.cursor()
        sqlite_select_query = """SELECT * from attractions"""
        cursor.execute(sqlite_select_query)
        records = cursor.fetchall()
        k = 0
        for row in records:
            if(row[3] == c.data):
                k = k + 1
                list1.append(row[0])
                list2.append(row[6])
                list3.append(row[5])
        bt = types.InlineKeyboardMarkup()
        for i in range(0, len(list1)):
            button = types.InlineKeyboardButton(text=list1[i], callback_data=list1[i] + "$")
            bt.add(button)
        back = types.InlineKeyboardButton(text='В главное меню', callback_data='main_menu')
        bt.add(back)
        botTimeWeb.send_message(c.message.chat.id, "найдено " + str(k) + " достопримечательностей", parse_mode='html', reply_markup=bt)
        cursor.close()
    if c.data[len(c.data) - 1:len(c.data)] == '$':
        for i in range(0, len(list1)):
            if(c.data == list1[i] + "$"):
                l = str(list3[i]) + '.jpg'
                botTimeWeb.send_photo(c.message.chat.id, open(l, 'rb'))
                bt2 = types.InlineKeyboardMarkup()
                back = types.InlineKeyboardButton(text='В главное меню', callback_data='main_menu')
                bt2.add(back)
                botTimeWeb.send_message(c.message.chat.id, list2[i], parse_mode='html', reply_markup=bt2)

botTimeWeb.infinity_polling()
